[package]
name = "compilador-portugues"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
lalrpop-util = "0.22.2"
logos = "0.15.0"
inkwell = { version = "0.6.0", features = ["llvm16-0"] }
anyhow = "1.0"